@startuml
class VisaApplicationData {
    + CreateVisaApplication() : bool
    + GetVisaApplicationByID(VisaApplicationID:int) : VisaApplication
}
IVisaApplicationData <|-- VisaApplicationData
@enduml
