// <auto-generated />
using AFS_Visa_Processing_System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AFS_Visa_Processing_System.Migrations
{
    [DbContext(typeof(AFS_Visa_Processing_SystemContext))]
    partial class AFS_Visa_Processing_SystemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AFS_Visa_Processing_System.Models.VisaApplication", b =>
                {
                    b.Property<int>("VisaAppID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisaAppID"));

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("VisaTypeID")
                        .HasColumnType("int");

                    b.HasKey("VisaAppID");

                    b.ToTable("VisaApplication");
                });
#pragma warning restore 612, 618
        }
    }
}
